### ISSUE TITLE
expireTime    单位错了

### ISSUE THREAD

**Issue by jaken150** [wyh-spring-ecosystem-student/spring-boot-student#2]
* @param expireTime    锁的过期时间(单位：秒)

 // 分布式服务器有时差，这里给1秒的误差值
            expires = System.currentTimeMillis() + expireTime + 1;
应该改为：
expires = System.currentTimeMillis() + expireTime * 1000  + 1*1000;
因为currentTimeMillis单位是毫秒，但你l输入参数定义的expireTime是秒的

**Comment by wyhmonstar** [comment]
恩 谢谢
